### ISSUE TITLE
v0.3.9 unuseable via spago

### ISSUE THREAD

**Issue by bbarker** [purescript-concur/purescript-concur-react#29]
I could be wrong about this, but i think moving things from src to lib has caused to to be unusable for me. This occurred after updating my package set today, and suddenly Concur modules couldn't be found. I looked at the diff between v0.3.9 and v0.3.8, and saw that files were moved from `src` to `lib/src`.

Previously, I had this issue for a dependency that I wrote, documented here: https://github.com/spacchetti/spago/issues/313

**Comment by ajnsit** [comment]
Ah, yeah that move might have caused issues. Let me take a look.

**Comment by ajnsit** [comment]
@bbarker so as far as I understand, moving the library sources back to the top level should fix this. I have made this change. Can you please test and let me know if this works for you?

**Comment by ajnsit** [comment]
Once you confirm, I will tag and release a new version of the lib.

**Comment by bbarker** [comment]
Hey, sorry for the delay in getting back, had a very busy weekend. 

So far, still getting a few errors, will try to investigate more:

```
[1/2 ModuleNotFound] .spago/concur-react/9887ce7c25699152ec138aefc2a3ba247fcef86c/src/Concur/React/Props.purs:10:1

  10  import React.Ref as Ref
      ^^^^^^^^^^^^^^^^^^^^^^^
  
  Module React.Ref was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.

[2/2 ModuleNotFound] .spago/concur-react/9887ce7c25699152ec138aefc2a3ba247fcef86c/src/Concur/React/Widgets.purs:12:1

  12  import React.Ref as Ref
      ^^^^^^^^^^^^^^^^^^^^^^^
  
  Module React.Ref was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.

```

**Comment by bbarker** [comment]
OK, it worked after upgrading my package set via spago :+1:

**Comment by paulyoung** [comment]
For anyone encountering this in future;

Despite the title of this issue, I was able to fix the `Module React.Ref was not found` errors by using `concur-react` `0.3.9` in `packages.dhall`. I believe that's the latest version of `concur-react` that supports `react` 7.
